version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    container_name: apigateway
    depends_on:
      - kafka
      - authservice
      - placementdriveservice
      # - studentservice
      # - notificationservice
      # - applicationservice

  authservice:
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    container_name: authservice
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "5001:8080"  # Need to remove port mapping in production


  placementdriveservice:
    build:
      context: .
      dockerfile: PlacementDriveService/Dockerfile
    container_name: placementdriveservice
    depends_on:
      - kafka
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "5002:8080"  # Need to remove port mapping in production


  # studentservice:
  #   build:
  #     context: .
  #     dockerfile: StudentService/Dockerfile
  #   container_name: studentservice
  #   depends_on:
  #     - kafka
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: Development
  #     KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  #   ports:
  #     - "5003:8080"  # Need to remove port mapping in production


  # notificationservice:
  #   build:
  #     context: .
  #     dockerfile: NotificationService/Dockerfile
  #   container_name: notificationservice
  #   depends_on:
  #     - kafka
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: Development
  #     KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  #   ports:
  #     - "5004:8080"  # Need to remove port mapping in production


  # applicationservice:
  #   build:
  #     context: .
  #     dockerfile: ApplicationService/Dockerfile
  #   container_name: applicationservice
  #   depends_on:
  #     - kafka
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: Development
  #     KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  #   ports:
  #     - "5005:8080"  # Need to remove port mapping in production